/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.automoto.view;

import com.automoto.model.BikeModel;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aashutoshdhakal
 */
public class AdminPanel extends javax.swing.JFrame {
    
    LinkedList<BikeModel> bikeList = new LinkedList<>();
    
    public void addBikes(BikeModel bikes){
       bikeList.add(bikes);
       DefaultTableModel model = (DefaultTableModel)tblBikeData.getModel();
       Object[] data =new Object[]{
            bikes.getBikeNumber(),bikes.getModel(),bikes.getCondition(), 
            bikes.getPrice()
        };  
       model.addRow(data);
    }
    
    
    private boolean checkBikeNo(BikeModel bikes) {
        for (BikeModel remainingBikes : bikeList) {
            if (remainingBikes.getBikeNumber() == bikes.getBikeNumber()) {
                   return true;
            }
        }
        return false;
    }
    
    private boolean deleteBikes(String bikeNumber, int selectedRow) {
        Iterator<BikeModel> iterator = bikeList.iterator();
        while (iterator.hasNext()) {
            BikeModel bikes = iterator.next();
            if (bikes.getBikeNumber() == bikeNumber) {
                // Remove the member from the list
                iterator.remove();

                // Also remove the row from the table
                DefaultTableModel model = (DefaultTableModel) tblBikeData.getModel();
                model.removeRow(selectedRow);
                return true; // Member deleted successfully
            }
        }
    return false; // No member found with the given ID
    }
    
    
    
    

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        panelAdminPanelHome.setVisible(true);
        panelAdminPanelRentalUpdate.setVisible(false);
        panelAdminPanelRentalDelete.setVisible(false);
        panelAdminPanelBikeAdd.setVisible(false);
        panelAdminPanelBikeUpdate.setVisible(false);
        panelAdminPanelBikeDelete.setVisible(false);
        panelAdminPanelBike.setVisible(false);
        panelAdminPanelBikeAddBike.setVisible(false);
        labelWarningBikeNo.setVisible(false);
        labelWarningBikeModel.setVisible(false);
        labelWarningBikeCondition.setVisible(false);
        labelWarningBikePrice.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAdminPanel = new javax.swing.JLabel();
        labelAdmin = new javax.swing.JLabel();
        buttonBikeManagement = new javax.swing.JButton();
        buttonRentalManagement = new javax.swing.JButton();
        buttonAdminPanelBack = new javax.swing.JButton();
        ButtonAdminPanelExit = new javax.swing.JButton();
        panelAdminPanelBikeAddBike = new javax.swing.JPanel();
        panelAdminPanelBikeAddBikePanel = new javax.swing.JPanel();
        labelEnterYourBikeDetail = new javax.swing.JLabel();
        fieldBikeNo = new javax.swing.JTextField();
        fieldBikeModel = new javax.swing.JTextField();
        fieldBikeCondition = new javax.swing.JTextField();
        fieldBikePrice = new javax.swing.JTextField();
        buttonAdd = new javax.swing.JButton();
        labelWarningBikeNo = new javax.swing.JLabel();
        labelWarningBikeModel = new javax.swing.JLabel();
        labelWarningBikeCondition = new javax.swing.JLabel();
        labelWarningBikePrice = new javax.swing.JLabel();
        labelAdminPanelBikeAddBike = new javax.swing.JLabel();
        panelAdminPanelBike = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBikeData = new javax.swing.JTable();
        panelAdminPanelHome = new javax.swing.JPanel();
        iconAdminPanelHomeImage = new javax.swing.JLabel();
        panelAdminPanelBikeAdd = new javax.swing.JPanel();
        labelAdminPanelBikeAdd = new javax.swing.JLabel();
        panelAdminPanelBikeUpdate = new javax.swing.JPanel();
        labelAdminPanelBikeUpdate = new javax.swing.JLabel();
        panelAdminPanelBikeDelete = new javax.swing.JPanel();
        labelAdminPanelBikeDelete = new javax.swing.JLabel();
        panelAdminPanelRentalUpdate = new javax.swing.JPanel();
        labelAdminPanelRentalUpdate = new javax.swing.JLabel();
        panelAdminPanelRentalDelete = new javax.swing.JPanel();
        labelAdminPanelRentalDelete = new javax.swing.JLabel();
        iconAdminPanelBase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1200));
        setMinimumSize(new java.awt.Dimension(1920, 1200));

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setLayout(null);

        labelAdminPanel.setFont(new java.awt.Font("Arial", 1, 52)); // NOI18N
        labelAdminPanel.setText("Admin Panel");
        jPanel1.add(labelAdminPanel);
        labelAdminPanel.setBounds(840, 80, 350, 50);

        labelAdmin.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        labelAdmin.setText("Admin");
        jPanel1.add(labelAdmin);
        labelAdmin.setBounds(150, 220, 160, 50);

        buttonBikeManagement.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        buttonBikeManagement.setText("Bike");
        buttonBikeManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBikeManagementMouseClicked(evt);
            }
        });
        jPanel1.add(buttonBikeManagement);
        buttonBikeManagement.setBounds(110, 390, 240, 60);

        buttonRentalManagement.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        buttonRentalManagement.setText("Rental");
        buttonRentalManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRentalManagementMouseClicked(evt);
            }
        });
        buttonRentalManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRentalManagementActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRentalManagement);
        buttonRentalManagement.setBounds(110, 480, 240, 60);

        buttonAdminPanelBack.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        buttonAdminPanelBack.setText("Back");
        buttonAdminPanelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAdminPanelBackMouseClicked(evt);
            }
        });
        buttonAdminPanelBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdminPanelBackActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAdminPanelBack);
        buttonAdminPanelBack.setBounds(110, 910, 240, 60);

        ButtonAdminPanelExit.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        ButtonAdminPanelExit.setText("Exit");
        ButtonAdminPanelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAdminPanelExitMouseClicked(evt);
            }
        });
        ButtonAdminPanelExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdminPanelExitActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAdminPanelExit);
        ButtonAdminPanelExit.setBounds(110, 1000, 240, 60);

        panelAdminPanelBikeAddBike.setBackground(new java.awt.Color(245, 245, 245));
        panelAdminPanelBikeAddBike.setMaximumSize(new java.awt.Dimension(1400, 732));
        panelAdminPanelBikeAddBike.setPreferredSize(new java.awt.Dimension(1400, 732));
        panelAdminPanelBikeAddBike.setSize(new java.awt.Dimension(1400, 732));
        panelAdminPanelBikeAddBike.setLayout(null);

        panelAdminPanelBikeAddBikePanel.setBackground(new java.awt.Color(226, 226, 226));
        panelAdminPanelBikeAddBikePanel.setLayout(null);

        labelEnterYourBikeDetail.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelEnterYourBikeDetail.setText("Enter Your Bike Detail");
        panelAdminPanelBikeAddBikePanel.add(labelEnterYourBikeDetail);
        labelEnterYourBikeDetail.setBounds(106, 19, 378, 42);

        fieldBikeNo.setBackground(new java.awt.Color(226, 226, 226));
        fieldBikeNo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fieldBikeNo.setBorder(javax.swing.BorderFactory.createTitledBorder("BIke No ."));
        panelAdminPanelBikeAddBikePanel.add(fieldBikeNo);
        fieldBikeNo.setBounds(19, 112, 561, 60);

        fieldBikeModel.setBackground(new java.awt.Color(226, 226, 226));
        fieldBikeModel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fieldBikeModel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bike Model."));
        panelAdminPanelBikeAddBikePanel.add(fieldBikeModel);
        fieldBikeModel.setBounds(20, 210, 561, 60);

        fieldBikeCondition.setBackground(new java.awt.Color(226, 226, 226));
        fieldBikeCondition.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fieldBikeCondition.setBorder(javax.swing.BorderFactory.createTitledBorder("Bike Condition"));
        panelAdminPanelBikeAddBikePanel.add(fieldBikeCondition);
        fieldBikeCondition.setBounds(20, 320, 561, 60);

        fieldBikePrice.setBackground(new java.awt.Color(226, 226, 226));
        fieldBikePrice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fieldBikePrice.setBorder(javax.swing.BorderFactory.createTitledBorder("Bike Price"));
        panelAdminPanelBikeAddBikePanel.add(fieldBikePrice);
        fieldBikePrice.setBounds(20, 430, 561, 60);

        buttonAdd.setBackground(new java.awt.Color(240, 84, 84));
        buttonAdd.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        buttonAdd.setText("Add");
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddMouseClicked(evt);
            }
        });
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        panelAdminPanelBikeAddBikePanel.add(buttonAdd);
        buttonAdd.setBounds(129, 548, 318, 51);

        labelWarningBikeNo.setForeground(new java.awt.Color(255, 0, 51));
        labelWarningBikeNo.setText("Warning");
        panelAdminPanelBikeAddBikePanel.add(labelWarningBikeNo);
        labelWarningBikeNo.setBounds(25, 168, 523, 17);

        labelWarningBikeModel.setForeground(new java.awt.Color(255, 0, 51));
        labelWarningBikeModel.setText("Warning");
        panelAdminPanelBikeAddBikePanel.add(labelWarningBikeModel);
        labelWarningBikeModel.setBounds(30, 270, 537, 17);

        labelWarningBikeCondition.setForeground(new java.awt.Color(255, 0, 51));
        labelWarningBikeCondition.setText("Warning");
        panelAdminPanelBikeAddBikePanel.add(labelWarningBikeCondition);
        labelWarningBikeCondition.setBounds(30, 380, 537, 17);

        labelWarningBikePrice.setForeground(new java.awt.Color(255, 0, 51));
        labelWarningBikePrice.setText("Warning");
        panelAdminPanelBikeAddBikePanel.add(labelWarningBikePrice);
        labelWarningBikePrice.setBounds(30, 490, 537, 17);

        panelAdminPanelBikeAddBike.add(panelAdminPanelBikeAddBikePanel);
        panelAdminPanelBikeAddBikePanel.setBounds(110, 60, 600, 620);

        labelAdminPanelBikeAddBike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automoto/resources/AddBike.png"))); // NOI18N
        panelAdminPanelBikeAddBike.add(labelAdminPanelBikeAddBike);
        labelAdminPanelBikeAddBike.setBounds(0, 0, 1400, 732);

        jPanel1.add(panelAdminPanelBikeAddBike);
        panelAdminPanelBikeAddBike.setBounds(440, 210, 1400, 732);

        panelAdminPanelBike.setBackground(new java.awt.Color(245, 245, 245));
        panelAdminPanelBike.setMaximumSize(new java.awt.Dimension(1400, 732));
        panelAdminPanelBike.setPreferredSize(new java.awt.Dimension(1400, 732));
        panelAdminPanelBike.setSize(new java.awt.Dimension(1400, 732));
        panelAdminPanelBike.setLayout(null);

        tblBikeData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bike No", "Bike Model", "Bike Condtion", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblBikeData);

        panelAdminPanelBike.add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 1400, 670);

        jPanel1.add(panelAdminPanelBike);
        panelAdminPanelBike.setBounds(440, 210, 1400, 732);

        panelAdminPanelHome.setBackground(new java.awt.Color(245, 245, 245));
        panelAdminPanelHome.setMaximumSize(new java.awt.Dimension(1400, 732));
        panelAdminPanelHome.setPreferredSize(new java.awt.Dimension(1400, 732));
        panelAdminPanelHome.setSize(new java.awt.Dimension(1400, 732));
        panelAdminPanelHome.setLayout(null);

        iconAdminPanelHomeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automoto/resources/WelcomeAdminPanel.png"))); // NOI18N
        panelAdminPanelHome.add(iconAdminPanelHomeImage);
        iconAdminPanelHomeImage.setBounds(10, 0, 1400, 730);

        jPanel1.add(panelAdminPanelHome);
        panelAdminPanelHome.setBounds(440, 210, 1400, 732);

        panelAdminPanelBikeAdd.setBackground(new java.awt.Color(245, 245, 245));
        panelAdminPanelBikeAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminPanelBikeAddMouseClicked(evt);
            }
        });

        labelAdminPanelBikeAdd.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        labelAdminPanelBikeAdd.setText("Add Bike");

        javax.swing.GroupLayout panelAdminPanelBikeAddLayout = new javax.swing.GroupLayout(panelAdminPanelBikeAdd);
        panelAdminPanelBikeAdd.setLayout(panelAdminPanelBikeAddLayout);
        panelAdminPanelBikeAddLayout.setHorizontalGroup(
            panelAdminPanelBikeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminPanelBikeAddLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(labelAdminPanelBikeAdd)
                .addGap(67, 67, 67))
        );
        panelAdminPanelBikeAddLayout.setVerticalGroup(
            panelAdminPanelBikeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminPanelBikeAddLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(labelAdminPanelBikeAdd)
                .addGap(17, 17, 17))
        );

        jPanel1.add(panelAdminPanelBikeAdd);
        panelAdminPanelBikeAdd.setBounds(470, 1020, 390, 100);

        panelAdminPanelBikeUpdate.setBackground(new java.awt.Color(245, 245, 245));
        panelAdminPanelBikeUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminPanelBikeUpdateMouseClicked(evt);
            }
        });

        labelAdminPanelBikeUpdate.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        labelAdminPanelBikeUpdate.setText("Update Bike");

        javax.swing.GroupLayout panelAdminPanelBikeUpdateLayout = new javax.swing.GroupLayout(panelAdminPanelBikeUpdate);
        panelAdminPanelBikeUpdate.setLayout(panelAdminPanelBikeUpdateLayout);
        panelAdminPanelBikeUpdateLayout.setHorizontalGroup(
            panelAdminPanelBikeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminPanelBikeUpdateLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(labelAdminPanelBikeUpdate)
                .addGap(67, 67, 67))
        );
        panelAdminPanelBikeUpdateLayout.setVerticalGroup(
            panelAdminPanelBikeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminPanelBikeUpdateLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(labelAdminPanelBikeUpdate)
                .addGap(17, 17, 17))
        );

        jPanel1.add(panelAdminPanelBikeUpdate);
        panelAdminPanelBikeUpdate.setBounds(910, 1020, 390, 100);

        panelAdminPanelBikeDelete.setBackground(new java.awt.Color(255, 87, 87));
        panelAdminPanelBikeDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminPanelBikeDeleteMouseClicked(evt);
            }
        });

        labelAdminPanelBikeDelete.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        labelAdminPanelBikeDelete.setText("Delete Bike");

        javax.swing.GroupLayout panelAdminPanelBikeDeleteLayout = new javax.swing.GroupLayout(panelAdminPanelBikeDelete);
        panelAdminPanelBikeDelete.setLayout(panelAdminPanelBikeDeleteLayout);
        panelAdminPanelBikeDeleteLayout.setHorizontalGroup(
            panelAdminPanelBikeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminPanelBikeDeleteLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(labelAdminPanelBikeDelete)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelAdminPanelBikeDeleteLayout.setVerticalGroup(
            panelAdminPanelBikeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminPanelBikeDeleteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelAdminPanelBikeDelete)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(panelAdminPanelBikeDelete);
        panelAdminPanelBikeDelete.setBounds(1420, 1020, 390, 100);

        panelAdminPanelRentalUpdate.setBackground(new java.awt.Color(245, 245, 245));

        labelAdminPanelRentalUpdate.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        labelAdminPanelRentalUpdate.setText("Update Rental");

        javax.swing.GroupLayout panelAdminPanelRentalUpdateLayout = new javax.swing.GroupLayout(panelAdminPanelRentalUpdate);
        panelAdminPanelRentalUpdate.setLayout(panelAdminPanelRentalUpdateLayout);
        panelAdminPanelRentalUpdateLayout.setHorizontalGroup(
            panelAdminPanelRentalUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminPanelRentalUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAdminPanelRentalUpdate)
                .addGap(240, 240, 240))
        );
        panelAdminPanelRentalUpdateLayout.setVerticalGroup(
            panelAdminPanelRentalUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminPanelRentalUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAdminPanelRentalUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelAdminPanelRentalUpdate);
        panelAdminPanelRentalUpdate.setBounds(730, 1040, 330, 60);

        panelAdminPanelRentalDelete.setBackground(new java.awt.Color(255, 87, 87));

        labelAdminPanelRentalDelete.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        labelAdminPanelRentalDelete.setText("Delete Rent");

        javax.swing.GroupLayout panelAdminPanelRentalDeleteLayout = new javax.swing.GroupLayout(panelAdminPanelRentalDelete);
        panelAdminPanelRentalDelete.setLayout(panelAdminPanelRentalDeleteLayout);
        panelAdminPanelRentalDeleteLayout.setHorizontalGroup(
            panelAdminPanelRentalDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminPanelRentalDeleteLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(labelAdminPanelRentalDelete)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        panelAdminPanelRentalDeleteLayout.setVerticalGroup(
            panelAdminPanelRentalDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminPanelRentalDeleteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelAdminPanelRentalDelete)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(panelAdminPanelRentalDelete);
        panelAdminPanelRentalDelete.setBounds(1420, 1020, 390, 100);

        iconAdminPanelBase.setBackground(new java.awt.Color(245, 245, 245));
        iconAdminPanelBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automoto/resources/AdminPanel.png"))); // NOI18N
        jPanel1.add(iconAdminPanelBase);
        iconAdminPanelBase.setBounds(0, 0, 1920, 1200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRentalManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRentalManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRentalManagementActionPerformed

    private void buttonAdminPanelBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdminPanelBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdminPanelBackActionPerformed

    private void ButtonAdminPanelExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdminPanelExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAdminPanelExitActionPerformed

    private void buttonAdminPanelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAdminPanelBackMouseClicked
        // TODO add your handling code here:
        new SelectionOption().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonAdminPanelBackMouseClicked

    private void ButtonAdminPanelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAdminPanelExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonAdminPanelExitMouseClicked

    private void buttonBikeManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBikeManagementMouseClicked
        // TODO add your handling code here:
        panelAdminPanelHome.setVisible(false);
        panelAdminPanelRentalUpdate.setVisible(false);
        panelAdminPanelRentalDelete.setVisible(false);
        panelAdminPanelBikeAdd.setVisible(true);
        panelAdminPanelBikeUpdate.setVisible(true);
        panelAdminPanelBikeDelete.setVisible(true);
        panelAdminPanelBike.setVisible(true);
        panelAdminPanelBikeAddBike.setVisible(false);
    }//GEN-LAST:event_buttonBikeManagementMouseClicked

    private void buttonRentalManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRentalManagementMouseClicked
        // TODO add your handling code here:
        panelAdminPanelHome.setVisible(false);
        panelAdminPanelRentalUpdate.setVisible(true);
        panelAdminPanelRentalDelete.setVisible(true);
        panelAdminPanelBikeAdd.setVisible(false);
        panelAdminPanelBikeUpdate.setVisible(false);
        panelAdminPanelBikeDelete.setVisible(false);
        panelAdminPanelBike.setVisible(false);
        panelAdminPanelBikeAddBike.setVisible(false);
    }//GEN-LAST:event_buttonRentalManagementMouseClicked

    private void panelAdminPanelBikeAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminPanelBikeAddMouseClicked
        // TODO add your handling code here:
        panelAdminPanelBikeAddBike.setVisible(true);
        panelAdminPanelBike.setVisible(false);
    }//GEN-LAST:event_panelAdminPanelBikeAddMouseClicked

    private void panelAdminPanelBikeUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminPanelBikeUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAdminPanelBikeUpdateMouseClicked

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseClicked
        // TODO add your handling code here:
        JTextField[] fields = {fieldBikeNo, fieldBikeModel, fieldBikeCondition, fieldBikePrice};
        JLabel[] labels = {labelWarningBikeNo, labelWarningBikeModel, labelWarningBikeCondition, labelWarningBikePrice};

        boolean hasEmptyFields = false;

        for (int i = 0; i < fields.length; i++) {
            if (fields[i].getText().isEmpty()) {
                labels[i].setText("This field is required!");
                labels[i].setVisible(true);                  
                hasEmptyFields = true;
            } else {
                labels[i].setVisible(false);
            }
        }

        // If any field is empty, stop further processing
        if (hasEmptyFields) {
            return;
        }
        
        
        ////////////////////////////////
        String bikeNo = (String)fieldBikeNo.getText();
        String bikeModel = fieldBikeModel.getText();
        String bikeCondition = fieldBikeCondition.getText();
        double bikePrice;

        
        try {
            bikePrice = Double.parseDouble(fieldBikePrice.getText());
        } catch (NumberFormatException e) {
            labelWarningBikePrice.setText("Please enter a valid number!");
            labelWarningBikePrice.setVisible(true);
            return;
        }
        

        boolean isValid=true;
           
        if (isValid) {
            BikeModel newBike = new BikeModel(bikeNo, bikeModel, bikeCondition, bikePrice);
            if (checkBikeNo(newBike)) {
               JOptionPane.showMessageDialog(null,"Duplicate Details.", "Duplicate", JOptionPane.INFORMATION_MESSAGE);

            } else {    
               addBikes(newBike);               
                JOptionPane.showMessageDialog(null,"Added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

        }
        
        panelAdminPanelBikeAddBike.setVisible(false);
        
        panelAdminPanelBike.setVisible(true);
        
    }//GEN-LAST:event_buttonAddMouseClicked

    private void panelAdminPanelBikeDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminPanelBikeDeleteMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblBikeData.getModel();
        int selectedRow = tblBikeData.getSelectedRow();

        if (selectedRow != -1) { // Check if a row is selected
            // Extract row data
            String bikeNumber = (String) tblBikeData.getValueAt(selectedRow, 0);
            int confirm = JOptionPane.showConfirmDialog(
            null, // Parent component
            "Are you sure you want to delete this Bike?", // Message
            "Confirm Deletion", // Title
            JOptionPane.YES_NO_OPTION, // Options
            JOptionPane.WARNING_MESSAGE );
            if (confirm == JOptionPane.YES_OPTION) {
                boolean deleted = deleteBikes(bikeNumber, selectedRow);
                if (deleted) {
                    JOptionPane.showMessageDialog(null, "Bike deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
            } 
        }else {
            JOptionPane.showMessageDialog(null, "Please select a Bike to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_panelAdminPanelBikeDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdminPanelExit;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonAdminPanelBack;
    private javax.swing.JButton buttonBikeManagement;
    private javax.swing.JButton buttonRentalManagement;
    private javax.swing.JTextField fieldBikeCondition;
    private javax.swing.JTextField fieldBikeModel;
    private javax.swing.JTextField fieldBikeNo;
    private javax.swing.JTextField fieldBikePrice;
    private javax.swing.JLabel iconAdminPanelBase;
    private javax.swing.JLabel iconAdminPanelHomeImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAdmin;
    private javax.swing.JLabel labelAdminPanel;
    private javax.swing.JLabel labelAdminPanelBikeAdd;
    private javax.swing.JLabel labelAdminPanelBikeAddBike;
    private javax.swing.JLabel labelAdminPanelBikeDelete;
    private javax.swing.JLabel labelAdminPanelBikeUpdate;
    private javax.swing.JLabel labelAdminPanelRentalDelete;
    private javax.swing.JLabel labelAdminPanelRentalUpdate;
    private javax.swing.JLabel labelEnterYourBikeDetail;
    private javax.swing.JLabel labelWarningBikeCondition;
    private javax.swing.JLabel labelWarningBikeModel;
    private javax.swing.JLabel labelWarningBikeNo;
    private javax.swing.JLabel labelWarningBikePrice;
    private javax.swing.JPanel panelAdminPanelBike;
    private javax.swing.JPanel panelAdminPanelBikeAdd;
    private javax.swing.JPanel panelAdminPanelBikeAddBike;
    private javax.swing.JPanel panelAdminPanelBikeAddBikePanel;
    private javax.swing.JPanel panelAdminPanelBikeDelete;
    private javax.swing.JPanel panelAdminPanelBikeUpdate;
    private javax.swing.JPanel panelAdminPanelHome;
    private javax.swing.JPanel panelAdminPanelRentalDelete;
    private javax.swing.JPanel panelAdminPanelRentalUpdate;
    private javax.swing.JTable tblBikeData;
    // End of variables declaration//GEN-END:variables
}
