/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.automoto.view;

import com.automoto.model.BikeModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author aashutoshdhakal
 */
public class QuickAction extends javax.swing.JFrame {

    /**
     * Creates new form QuickAction
     */
    public QuickAction() {
        initComponents();
        panelDecuration2.setVisible(false);
        panelDecuration3.setVisible(false);
        panelRent.setVisible(false);
        panelReturn.setVisible(false);
        labelRentWarningFirstName.setVisible(false);
        labelRentWarningLastName.setVisible(false);
        labelRentWarningDateOfBirth.setVisible(false);
        labelRentWarningLicenceNo.setVisible(false);
        labelRentWarningDocumentNo.setVisible(false);
        labelRentWarningMobileNo.setVisible(false);
        labelReturnWarningFirstName.setVisible(false);
        labelReturnWarningLastName.setVisible(false);
        labelReturnWarningLicenceNo.setVisible(false);
        labelReturnWarningDocumentNo.setVisible(false);
        labelReturnWarningMobileNo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelQuickAction = new javax.swing.JLabel();
        buttonHome = new javax.swing.JButton();
        buttonRent = new javax.swing.JButton();
        buttonReturn = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        iconQuickActionBase = new javax.swing.JLabel();
        panelRent = new javax.swing.JPanel();
        labelRentTopic = new javax.swing.JLabel();
        fieldRentFirstName = new javax.swing.JTextField();
        labelRentFirstName = new javax.swing.JLabel();
        fieldRentLastName = new javax.swing.JTextField();
        labelRentLastName = new javax.swing.JLabel();
        fieldRentLicenceNo = new javax.swing.JTextField();
        labelRentLicenceNo = new javax.swing.JLabel();
        labelRentDocumentType = new javax.swing.JLabel();
        comboBoxRentDocumentType = new javax.swing.JComboBox<>();
        sliderRentDurationOfRent = new javax.swing.JSlider();
        labelRentDurartionOfRent = new javax.swing.JLabel();
        labelRentGender = new javax.swing.JLabel();
        radioButtonRentMale = new javax.swing.JRadioButton();
        radioButtonRentFemale = new javax.swing.JRadioButton();
        labelRentDateOfBirth = new javax.swing.JLabel();
        labelRentDocumentNo = new javax.swing.JLabel();
        fieldRentDocumentNo = new javax.swing.JTextField();
        checkboxRentBikeModel = new javax.swing.JComboBox<>();
        labelRentBikeModel = new javax.swing.JLabel();
        fieldRentDateOfBirth = new javax.swing.JTextField();
        labelRentMobileNo = new javax.swing.JLabel();
        fieldRentMobileNo = new javax.swing.JTextField();
        radioButtonRentOthers = new javax.swing.JRadioButton();
        buttonRentBike = new javax.swing.JButton();
        labelRentWarningFirstName = new javax.swing.JLabel();
        labelRentWarningLastName = new javax.swing.JLabel();
        labelRentWarningDateOfBirth = new javax.swing.JLabel();
        labelRentWarningMobileNo = new javax.swing.JLabel();
        labelRentWarningLicenceNo = new javax.swing.JLabel();
        labelRentWarningDocumentNo = new javax.swing.JLabel();
        pnlRentBikePictureDisplay = new javax.swing.JPanel();
        iconRentBanner = new javax.swing.JLabel();
        panelReturn = new javax.swing.JPanel();
        labelRentTopic2 = new javax.swing.JLabel();
        fieldReturnFirstName = new javax.swing.JTextField();
        labelReturnFirstName = new javax.swing.JLabel();
        fieldReturnLastName = new javax.swing.JTextField();
        labelReturnLastName = new javax.swing.JLabel();
        fieldReturnLicenceNo = new javax.swing.JTextField();
        labelReturnLicenceNo = new javax.swing.JLabel();
        labelReturnDocumentType = new javax.swing.JLabel();
        comboBoxReturnDocumentType = new javax.swing.JComboBox<>();
        labelReturnDocumentNo = new javax.swing.JLabel();
        fieldReturnDocumentNo = new javax.swing.JTextField();
        comboBoxReturnBikeModel = new javax.swing.JComboBox<>();
        labelReturnBikeModel = new javax.swing.JLabel();
        labelReturnMobileNo = new javax.swing.JLabel();
        fieldReturnMobileNo = new javax.swing.JTextField();
        labelReturnWarningMobileNo = new javax.swing.JLabel();
        labelReturnWarningFirstName = new javax.swing.JLabel();
        labelReturnWarningLastName = new javax.swing.JLabel();
        labelReturnWarningLicenceNo = new javax.swing.JLabel();
        labelReturnWarningDocumentNo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pnlReturnBannerBase = new javax.swing.JPanel();
        iconReturnBanner = new javax.swing.JLabel();
        panelDecuration1 = new javax.swing.JPanel();
        panelDecuration2 = new javax.swing.JPanel();
        panelDecuration3 = new javax.swing.JPanel();
        IconQuickActionBaseplate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1200));

        jPanel1.setBackground(new java.awt.Color(48, 71, 94));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setLayout(null);

        labelQuickAction.setFont(new java.awt.Font("Silom", 1, 64)); // NOI18N
        labelQuickAction.setForeground(new java.awt.Color(240, 84, 84));
        labelQuickAction.setText("Quick Action");
        jPanel1.add(labelQuickAction);
        labelQuickAction.setBounds(740, 70, 460, 70);

        buttonHome.setBackground(new java.awt.Color(240, 84, 84));
        buttonHome.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        buttonHome.setForeground(new java.awt.Color(255, 255, 255));
        buttonHome.setText("Home");
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHomeMouseClicked(evt);
            }
        });
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(buttonHome);
        buttonHome.setBounds(110, 250, 220, 100);

        buttonRent.setBackground(new java.awt.Color(240, 84, 84));
        buttonRent.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        buttonRent.setForeground(new java.awt.Color(255, 255, 255));
        buttonRent.setText("Rent");
        buttonRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRentMouseClicked(evt);
            }
        });
        buttonRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRentActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRent);
        buttonRent.setBounds(110, 380, 220, 100);

        buttonReturn.setBackground(new java.awt.Color(240, 84, 84));
        buttonReturn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        buttonReturn.setForeground(new java.awt.Color(255, 255, 255));
        buttonReturn.setText("Return");
        buttonReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonReturnMouseClicked(evt);
            }
        });
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });
        jPanel1.add(buttonReturn);
        buttonReturn.setBounds(110, 510, 220, 100);

        buttonBack.setBackground(new java.awt.Color(240, 84, 84));
        buttonBack.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setText("Back");
        buttonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBackMouseClicked(evt);
            }
        });
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBack);
        buttonBack.setBounds(110, 830, 220, 100);

        buttonExit.setBackground(new java.awt.Color(240, 84, 84));
        buttonExit.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setText("Exit");
        buttonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonExitMouseClicked(evt);
            }
        });
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        jPanel1.add(buttonExit);
        buttonExit.setBounds(110, 960, 220, 100);

        panelHome.setBackground(new java.awt.Color(245, 245, 245));
        panelHome.setMaximumSize(new java.awt.Dimension(1390, 880));
        panelHome.setLayout(null);

        iconQuickActionBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automoto/resources/QuickActionHome.png"))); // NOI18N
        panelHome.add(iconQuickActionBase);
        iconQuickActionBase.setBounds(0, 0, 1390, 880);

        jPanel1.add(panelHome);
        panelHome.setBounds(430, 220, 1390, 880);

        panelRent.setBackground(new java.awt.Color(245, 245, 245));
        panelRent.setMaximumSize(new java.awt.Dimension(1390, 880));
        panelRent.setMinimumSize(new java.awt.Dimension(1390, 880));
        panelRent.setPreferredSize(new java.awt.Dimension(1390, 880));
        panelRent.setLayout(null);

        labelRentTopic.setFont(new java.awt.Font("PT Mono", 1, 48)); // NOI18N
        labelRentTopic.setText("Enter The Rent Details Here");
        panelRent.add(labelRentTopic);
        labelRentTopic.setBounds(310, 50, 783, 55);

        fieldRentFirstName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelRent.add(fieldRentFirstName);
        fieldRentFirstName.setBounds(380, 170, 341, 38);

        labelRentFirstName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRentFirstName.setText("First Name :");
        panelRent.add(labelRentFirstName);
        labelRentFirstName.setBounds(110, 170, 149, 36);

        fieldRentLastName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelRent.add(fieldRentLastName);
        fieldRentLastName.setBounds(380, 240, 341, 38);

        labelRentLastName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRentLastName.setText("Last Name :");
        panelRent.add(labelRentLastName);
        labelRentLastName.setBounds(110, 240, 135, 38);

        fieldRentLicenceNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldRentLicenceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRentLicenceNoActionPerformed(evt);
            }
        });
        panelRent.add(fieldRentLicenceNo);
        fieldRentLicenceNo.setBounds(380, 500, 340, 40);

        labelRentLicenceNo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRentLicenceNo.setText("Licence No :");
        panelRent.add(labelRentLicenceNo);
        labelRentLicenceNo.setBounds(110, 500, 143, 40);

        labelRentDocumentType.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRentDocumentType.setText("Document Type:");
        panelRent.add(labelRentDocumentType);
        labelRentDocumentType.setBounds(110, 580, 188, 28);

        comboBoxRentDocumentType.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comboBoxRentDocumentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Citizenship", "National ID" }));
        comboBoxRentDocumentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRentDocumentTypeActionPerformed(evt);
            }
        });
        panelRent.add(comboBoxRentDocumentType);
        comboBoxRentDocumentType.setBounds(380, 570, 339, 40);

        sliderRentDurationOfRent.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        panelRent.add(sliderRentDurationOfRent);
        sliderRentDurationOfRent.setBounds(380, 710, 340, 30);

        labelRentDurartionOfRent.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRentDurartionOfRent.setText("Duration of Rent :");
        panelRent.add(labelRentDurartionOfRent);
        labelRentDurartionOfRent.setBounds(110, 710, 204, 28);

        labelRentGender.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRentGender.setText("Gender :");
        panelRent.add(labelRentGender);
        labelRentGender.setBounds(110, 370, 99, 40);

        buttonGroupGender.add(radioButtonRentMale);
        radioButtonRentMale.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        radioButtonRentMale.setText("Male");
        radioButtonRentMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonRentMaleActionPerformed(evt);
            }
        });
        panelRent.add(radioButtonRentMale);
        radioButtonRentMale.setBounds(380, 380, 63, 26);

        buttonGroupGender.add(radioButtonRentFemale);
        radioButtonRentFemale.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        radioButtonRentFemale.setText("Female");
        panelRent.add(radioButtonRentFemale);
        radioButtonRentFemale.setBounds(490, 380, 85, 26);

        labelRentDateOfBirth.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRentDateOfBirth.setText("Date Of Birth :");
        panelRent.add(labelRentDateOfBirth);
        labelRentDateOfBirth.setBounds(110, 320, 163, 28);

        labelRentDocumentNo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRentDocumentNo.setText("Document No :");
        panelRent.add(labelRentDocumentNo);
        labelRentDocumentNo.setBounds(110, 640, 171, 40);

        fieldRentDocumentNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldRentDocumentNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRentDocumentNoActionPerformed(evt);
            }
        });
        panelRent.add(fieldRentDocumentNo);
        fieldRentDocumentNo.setBounds(380, 640, 340, 40);

        checkboxRentBikeModel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        checkboxRentBikeModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Model" }));
        panelRent.add(checkboxRentBikeModel);
        checkboxRentBikeModel.setBounds(380, 430, 340, 39);

        labelRentBikeModel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRentBikeModel.setText("Bike Model :");
        panelRent.add(labelRentBikeModel);
        labelRentBikeModel.setBounds(110, 430, 142, 41);

        fieldRentDateOfBirth.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelRent.add(fieldRentDateOfBirth);
        fieldRentDateOfBirth.setBounds(380, 310, 342, 37);

        labelRentMobileNo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRentMobileNo.setText("Mobile No :");
        panelRent.add(labelRentMobileNo);
        labelRentMobileNo.setBounds(110, 770, 131, 30);

        fieldRentMobileNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelRent.add(fieldRentMobileNo);
        fieldRentMobileNo.setBounds(380, 763, 340, 40);

        buttonGroupGender.add(radioButtonRentOthers);
        radioButtonRentOthers.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        radioButtonRentOthers.setText("Others");
        radioButtonRentOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonRentOthersActionPerformed(evt);
            }
        });
        panelRent.add(radioButtonRentOthers);
        radioButtonRentOthers.setBounds(610, 380, 81, 26);

        buttonRentBike.setBackground(new java.awt.Color(240, 84, 84));
        buttonRentBike.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        buttonRentBike.setText("Rent");
        buttonRentBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRentBikeMouseClicked(evt);
            }
        });
        buttonRentBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRentBikeActionPerformed(evt);
            }
        });
        panelRent.add(buttonRentBike);
        buttonRentBike.setBounds(830, 740, 450, 50);

        labelRentWarningFirstName.setForeground(new java.awt.Color(255, 51, 0));
        labelRentWarningFirstName.setText("Warning");
        panelRent.add(labelRentWarningFirstName);
        labelRentWarningFirstName.setBounds(384, 210, 330, 17);

        labelRentWarningLastName.setForeground(new java.awt.Color(255, 51, 0));
        labelRentWarningLastName.setText("Warning");
        panelRent.add(labelRentWarningLastName);
        labelRentWarningLastName.setBounds(380, 280, 340, 17);

        labelRentWarningDateOfBirth.setForeground(new java.awt.Color(255, 51, 0));
        labelRentWarningDateOfBirth.setText("Warning");
        panelRent.add(labelRentWarningDateOfBirth);
        labelRentWarningDateOfBirth.setBounds(380, 350, 340, 17);

        labelRentWarningMobileNo.setForeground(new java.awt.Color(255, 51, 0));
        labelRentWarningMobileNo.setText("Warning");
        panelRent.add(labelRentWarningMobileNo);
        labelRentWarningMobileNo.setBounds(380, 800, 340, 20);

        labelRentWarningLicenceNo.setForeground(new java.awt.Color(255, 51, 0));
        labelRentWarningLicenceNo.setText("Warning");
        panelRent.add(labelRentWarningLicenceNo);
        labelRentWarningLicenceNo.setBounds(380, 540, 340, 17);

        labelRentWarningDocumentNo.setForeground(new java.awt.Color(255, 51, 0));
        labelRentWarningDocumentNo.setText("Warning");
        panelRent.add(labelRentWarningDocumentNo);
        labelRentWarningDocumentNo.setBounds(380, 680, 340, 17);

        pnlRentBikePictureDisplay.setBackground(new java.awt.Color(255, 255, 255));
        pnlRentBikePictureDisplay.setMaximumSize(new java.awt.Dimension(450, 560));
        pnlRentBikePictureDisplay.setMinimumSize(new java.awt.Dimension(450, 560));
        pnlRentBikePictureDisplay.setPreferredSize(new java.awt.Dimension(450, 560));
        pnlRentBikePictureDisplay.setLayout(null);

        iconRentBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automoto/resources/RentBanner.png"))); // NOI18N
        pnlRentBikePictureDisplay.add(iconRentBanner);
        iconRentBanner.setBounds(0, 0, 450, 560);

        panelRent.add(pnlRentBikePictureDisplay);
        pnlRentBikePictureDisplay.setBounds(830, 180, 450, 560);

        jPanel1.add(panelRent);
        panelRent.setBounds(430, 220, 1390, 880);

        panelReturn.setBackground(new java.awt.Color(245, 245, 245));
        panelReturn.setMaximumSize(new java.awt.Dimension(1390, 880));
        panelReturn.setMinimumSize(new java.awt.Dimension(1390, 880));
        panelReturn.setPreferredSize(new java.awt.Dimension(1390, 880));
        panelReturn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRentTopic2.setFont(new java.awt.Font("PT Mono", 1, 48)); // NOI18N
        labelRentTopic2.setText("Enter The Return Details Here");
        panelReturn.add(labelRentTopic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        fieldReturnFirstName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelReturn.add(fieldReturnFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 341, 38));

        labelReturnFirstName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelReturnFirstName.setText("First Name :");
        panelReturn.add(labelReturnFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 149, 36));

        fieldReturnLastName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelReturn.add(fieldReturnLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 341, 38));

        labelReturnLastName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelReturnLastName.setText("Last Name :");
        panelReturn.add(labelReturnLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, 38));

        fieldReturnLicenceNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldReturnLicenceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldReturnLicenceNoActionPerformed(evt);
            }
        });
        panelReturn.add(fieldReturnLicenceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 340, 40));

        labelReturnLicenceNo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelReturnLicenceNo.setText("Licence No :");
        panelReturn.add(labelReturnLicenceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        labelReturnDocumentType.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelReturnDocumentType.setText("Document Type:");
        panelReturn.add(labelReturnDocumentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        comboBoxReturnDocumentType.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comboBoxReturnDocumentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Citizenship No", "National ID" }));
        panelReturn.add(comboBoxReturnDocumentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 339, 40));

        labelReturnDocumentNo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelReturnDocumentNo.setText("Document No :");
        panelReturn.add(labelReturnDocumentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, -1, 40));

        fieldReturnDocumentNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldReturnDocumentNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldReturnDocumentNoActionPerformed(evt);
            }
        });
        panelReturn.add(fieldReturnDocumentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, 340, 38));

        comboBoxReturnBikeModel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comboBoxReturnBikeModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Model" }));
        panelReturn.add(comboBoxReturnBikeModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 340, 39));

        labelReturnBikeModel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelReturnBikeModel.setText("Bike Model :");
        panelReturn.add(labelReturnBikeModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, 41));

        labelReturnMobileNo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelReturnMobileNo.setText("Mobile No :");
        panelReturn.add(labelReturnMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 740, -1, 30));

        fieldReturnMobileNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelReturn.add(fieldReturnMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 730, 340, 40));

        labelReturnWarningMobileNo.setForeground(new java.awt.Color(255, 0, 0));
        labelReturnWarningMobileNo.setText("Warning");
        panelReturn.add(labelReturnWarningMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 770, 340, -1));

        labelReturnWarningFirstName.setForeground(new java.awt.Color(255, 0, 0));
        labelReturnWarningFirstName.setText("Warning");
        panelReturn.add(labelReturnWarningFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 340, -1));

        labelReturnWarningLastName.setForeground(new java.awt.Color(255, 0, 0));
        labelReturnWarningLastName.setText("Warning");
        panelReturn.add(labelReturnWarningLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 340, -1));

        labelReturnWarningLicenceNo.setForeground(new java.awt.Color(255, 0, 0));
        labelReturnWarningLicenceNo.setText("Warning");
        panelReturn.add(labelReturnWarningLicenceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 340, -1));

        labelReturnWarningDocumentNo.setForeground(new java.awt.Color(255, 0, 0));
        labelReturnWarningDocumentNo.setText("Warning");
        panelReturn.add(labelReturnWarningDocumentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, 340, -1));

        jButton2.setBackground(new java.awt.Color(240, 84, 84));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jButton2.setText("Return");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelReturn.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 740, 450, 50));

        pnlReturnBannerBase.setBackground(new java.awt.Color(255, 255, 255));
        pnlReturnBannerBase.setMaximumSize(new java.awt.Dimension(450, 560));
        pnlReturnBannerBase.setMinimumSize(new java.awt.Dimension(450, 560));
        pnlReturnBannerBase.setPreferredSize(new java.awt.Dimension(450, 560));

        iconReturnBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automoto/resources/ReturnBanner.png"))); // NOI18N

        javax.swing.GroupLayout pnlReturnBannerBaseLayout = new javax.swing.GroupLayout(pnlReturnBannerBase);
        pnlReturnBannerBase.setLayout(pnlReturnBannerBaseLayout);
        pnlReturnBannerBaseLayout.setHorizontalGroup(
            pnlReturnBannerBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconReturnBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlReturnBannerBaseLayout.setVerticalGroup(
            pnlReturnBannerBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconReturnBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelReturn.add(pnlReturnBannerBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, -1, -1));

        jPanel1.add(panelReturn);
        panelReturn.setBounds(430, 220, 1390, 880);

        panelDecuration1.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout panelDecuration1Layout = new javax.swing.GroupLayout(panelDecuration1);
        panelDecuration1.setLayout(panelDecuration1Layout);
        panelDecuration1Layout.setHorizontalGroup(
            panelDecuration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelDecuration1Layout.setVerticalGroup(
            panelDecuration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(panelDecuration1);
        panelDecuration1.setBounds(360, 240, 50, 120);

        panelDecuration2.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout panelDecuration2Layout = new javax.swing.GroupLayout(panelDecuration2);
        panelDecuration2.setLayout(panelDecuration2Layout);
        panelDecuration2Layout.setHorizontalGroup(
            panelDecuration2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelDecuration2Layout.setVerticalGroup(
            panelDecuration2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(panelDecuration2);
        panelDecuration2.setBounds(360, 370, 50, 120);

        panelDecuration3.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout panelDecuration3Layout = new javax.swing.GroupLayout(panelDecuration3);
        panelDecuration3.setLayout(panelDecuration3Layout);
        panelDecuration3Layout.setHorizontalGroup(
            panelDecuration3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelDecuration3Layout.setVerticalGroup(
            panelDecuration3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(panelDecuration3);
        panelDecuration3.setBounds(360, 500, 50, 120);

        IconQuickActionBaseplate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automoto/resources/QuickActionBasePlate.png"))); // NOI18N
        jPanel1.add(IconQuickActionBaseplate);
        IconQuickActionBaseplate.setBounds(0, 0, 1920, 1200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRentActionPerformed

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReturnActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void buttonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseClicked
        // TODO add your handling code here:
        panelDecuration1.setVisible(true);
        panelDecuration2.setVisible(false);
        panelDecuration3.setVisible(false);
        panelHome.setVisible(true);
        panelRent.setVisible(false);
        panelReturn.setVisible(false);
    }//GEN-LAST:event_buttonHomeMouseClicked

    private void buttonRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRentMouseClicked
        // TODO add your handling code here:
        panelDecuration2.setVisible(true);
        panelDecuration1.setVisible(false);
        panelDecuration3.setVisible(false);
        panelHome.setVisible(false);
        panelRent.setVisible(true);
        panelReturn.setVisible(false);
    }//GEN-LAST:event_buttonRentMouseClicked

    private void buttonReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonReturnMouseClicked
        // TODO add your handling code here:
        panelDecuration3.setVisible(true);
        panelDecuration1.setVisible(false);
        panelDecuration2.setVisible(false);
        panelHome.setVisible(false);
        panelRent.setVisible(false);
        panelReturn.setVisible(true);
    }//GEN-LAST:event_buttonReturnMouseClicked

    private void buttonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new SelectionOption().setVisible(true);
    }//GEN-LAST:event_buttonBackMouseClicked

    private void buttonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitMouseClicked

    private void fieldRentLicenceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRentLicenceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRentLicenceNoActionPerformed

    private void radioButtonRentMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonRentMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonRentMaleActionPerformed

    private void fieldRentDocumentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRentDocumentNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRentDocumentNoActionPerformed

    private void fieldReturnLicenceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldReturnLicenceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldReturnLicenceNoActionPerformed

    private void fieldReturnDocumentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldReturnDocumentNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldReturnDocumentNoActionPerformed

    private void radioButtonRentOthersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonRentOthersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonRentOthersActionPerformed

    private void comboBoxRentDocumentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRentDocumentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxRentDocumentTypeActionPerformed

    private void buttonRentBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRentBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRentBikeActionPerformed

    private void buttonRentBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRentBikeMouseClicked
        // TODO add your handling code here: 
        JTextField[] fields = {fieldRentFirstName, fieldRentLastName, fieldRentDateOfBirth, fieldRentLicenceNo, fieldRentDocumentNo, fieldRentMobileNo};
        JLabel[] labels = {labelRentWarningFirstName, labelRentWarningLastName, labelRentWarningDateOfBirth, labelRentWarningLicenceNo, labelRentWarningDocumentNo, labelRentWarningMobileNo};

        boolean hasEmptyFields = false;

        for (int i = 0; i < fields.length; i++) {
            if (fields[i].getText().isEmpty()) {
                labels[i].setText("This field is required!");
                labels[i].setVisible(true);                  
                hasEmptyFields = true;
            } else {
                labels[i].setVisible(false);
            }
        }

        // If any field is empty, stop further processing
        if (hasEmptyFields) {
            return;
        }
        
        //////////////////////////
        String firstName = fieldRentFirstName.getText();
        String lastName = fieldRentLastName.getText();
        String dOB = fieldRentDateOfBirth.getText();
        long documentNo;
        long licenceNo;
        long mobileNo;
        String documentType = (String) comboBoxRentDocumentType.getSelectedItem();

        try {
            licenceNo = Long.parseLong(fieldRentLicenceNo.getText());
        } catch (NumberFormatException e) {
            labelRentWarningLicenceNo.setText("Please enter a valid number!");
            labelRentWarningLicenceNo.setVisible(true);
            return;
        }
        
        try {
            documentNo = Long.parseLong(fieldRentDocumentNo.getText());
        } catch (NumberFormatException e) {
            labelRentWarningDocumentNo.setText("Please enter a valid number!");
            labelRentWarningDocumentNo.setVisible(true);
            return;
        }
        
        try {
            mobileNo = Long.parseLong(fieldRentMobileNo.getText());
        } catch (NumberFormatException e) {
            labelRentWarningMobileNo.setText("Please enter a valid number!");
            labelRentWarningMobileNo.setVisible(true);
            return;
        }
        
        if(!radioButtonRentMale.isSelected() && !radioButtonRentFemale.isSelected() && !radioButtonRentOthers.isSelected()){
            JOptionPane.showMessageDialog(null, "Gender is not selected. Please select a gender!","Error",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "Bike Renturned successfully!");
        
        //////////////////////////
        
        

    }//GEN-LAST:event_buttonRentBikeMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        JTextField[] fields = {fieldReturnFirstName, fieldReturnLastName, fieldReturnLicenceNo, fieldReturnDocumentNo, fieldReturnMobileNo};
        JLabel[] labels = {labelReturnWarningFirstName, labelReturnWarningLastName, labelReturnWarningLicenceNo, labelReturnWarningDocumentNo, labelReturnWarningMobileNo};

        boolean hasEmptyFields = false;

        for (int i = 0; i < fields.length; i++) {
            if (fields[i].getText().isEmpty()) {
                labels[i].setText("This field is required!");
                labels[i].setVisible(true);                  
                hasEmptyFields = true;
            } else {
                labels[i].setVisible(false);
            }
        }

        // If any field is empty, stop further processing
        if (hasEmptyFields) {
            return;
        }
        
        
        ////////////////////////////////
        String firstName = fieldReturnFirstName.getText();
        String lastName = fieldReturnLastName.getText();
        long documentNo;
        long licenceNo;
        long mobileNo;
        String documentType = (String) comboBoxReturnDocumentType.getSelectedItem();
        
        try {
            licenceNo = Long.parseLong(fieldReturnLicenceNo.getText());
        } catch (NumberFormatException e) {
            labelReturnWarningLicenceNo.setText("Please enter a valid number!");
            labelReturnWarningLicenceNo.setVisible(true);
            return;
        }
        
        try {
            documentNo = Long.parseLong(fieldReturnDocumentNo.getText());
        } catch (NumberFormatException e) {
            labelReturnWarningDocumentNo.setText("Please enter a valid number!");
            labelReturnWarningDocumentNo.setVisible(true);
            return;
        }
        
        try {
            mobileNo = Long.parseLong(fieldReturnMobileNo.getText());
        } catch (NumberFormatException e) {
            labelReturnWarningMobileNo.setText("Please enter a valid number!");
            labelReturnWarningMobileNo.setVisible(true);
            return;
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "Bike Rented successfully!");
        ////////////////////////////////
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuickAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuickAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuickAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuickAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuickAction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconQuickActionBaseplate;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonExit;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonRent;
    private javax.swing.JButton buttonRentBike;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JComboBox<String> checkboxRentBikeModel;
    private javax.swing.JComboBox<String> comboBoxRentDocumentType;
    private javax.swing.JComboBox<String> comboBoxReturnBikeModel;
    private javax.swing.JComboBox<String> comboBoxReturnDocumentType;
    private javax.swing.JTextField fieldRentDateOfBirth;
    private javax.swing.JTextField fieldRentDocumentNo;
    private javax.swing.JTextField fieldRentFirstName;
    private javax.swing.JTextField fieldRentLastName;
    private javax.swing.JTextField fieldRentLicenceNo;
    private javax.swing.JTextField fieldRentMobileNo;
    private javax.swing.JTextField fieldReturnDocumentNo;
    private javax.swing.JTextField fieldReturnFirstName;
    private javax.swing.JTextField fieldReturnLastName;
    private javax.swing.JTextField fieldReturnLicenceNo;
    private javax.swing.JTextField fieldReturnMobileNo;
    private javax.swing.JLabel iconQuickActionBase;
    private javax.swing.JLabel iconRentBanner;
    private javax.swing.JLabel iconReturnBanner;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelQuickAction;
    private javax.swing.JLabel labelRentBikeModel;
    private javax.swing.JLabel labelRentDateOfBirth;
    private javax.swing.JLabel labelRentDocumentNo;
    private javax.swing.JLabel labelRentDocumentType;
    private javax.swing.JLabel labelRentDurartionOfRent;
    private javax.swing.JLabel labelRentFirstName;
    private javax.swing.JLabel labelRentGender;
    private javax.swing.JLabel labelRentLastName;
    private javax.swing.JLabel labelRentLicenceNo;
    private javax.swing.JLabel labelRentMobileNo;
    private javax.swing.JLabel labelRentTopic;
    private javax.swing.JLabel labelRentTopic2;
    private javax.swing.JLabel labelRentWarningDateOfBirth;
    private javax.swing.JLabel labelRentWarningDocumentNo;
    private javax.swing.JLabel labelRentWarningFirstName;
    private javax.swing.JLabel labelRentWarningLastName;
    private javax.swing.JLabel labelRentWarningLicenceNo;
    private javax.swing.JLabel labelRentWarningMobileNo;
    private javax.swing.JLabel labelReturnBikeModel;
    private javax.swing.JLabel labelReturnDocumentNo;
    private javax.swing.JLabel labelReturnDocumentType;
    private javax.swing.JLabel labelReturnFirstName;
    private javax.swing.JLabel labelReturnLastName;
    private javax.swing.JLabel labelReturnLicenceNo;
    private javax.swing.JLabel labelReturnMobileNo;
    private javax.swing.JLabel labelReturnWarningDocumentNo;
    private javax.swing.JLabel labelReturnWarningFirstName;
    private javax.swing.JLabel labelReturnWarningLastName;
    private javax.swing.JLabel labelReturnWarningLicenceNo;
    private javax.swing.JLabel labelReturnWarningMobileNo;
    private javax.swing.JPanel panelDecuration1;
    private javax.swing.JPanel panelDecuration2;
    private javax.swing.JPanel panelDecuration3;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelRent;
    private javax.swing.JPanel panelReturn;
    private javax.swing.JPanel pnlRentBikePictureDisplay;
    private javax.swing.JPanel pnlReturnBannerBase;
    private javax.swing.JRadioButton radioButtonRentFemale;
    private javax.swing.JRadioButton radioButtonRentMale;
    private javax.swing.JRadioButton radioButtonRentOthers;
    private javax.swing.JSlider sliderRentDurationOfRent;
    // End of variables declaration//GEN-END:variables
}
